package com.aifriend.assistant.domain;

/**
 * 与OpenAPI AssistantReasonCode同步的固定原因，模型不得自行扩展。
 * @author codex
 * @since 1.0.0
 */
public enum AssistantReason {
    /** 协议原因 NONE。 */ NONE,
    /** 协议原因 EMPTY_INPUT。 */ EMPTY_INPUT,
    /** 协议原因 INVALID_TEXT。 */ INVALID_TEXT,
    /** 协议原因 INPUT_LIMIT。 */ INPUT_LIMIT,
    /** 协议原因 INVALID_REQUEST。 */ INVALID_REQUEST,
    /** 协议原因 AMBIGUOUS_QUERY。 */ AMBIGUOUS_QUERY,
    /** 协议原因 UNCERTAIN_TRANSCRIPT。 */ UNCERTAIN_TRANSCRIPT,
    /** 协议原因 OUT_OF_SCOPE。 */ OUT_OF_SCOPE,
    /** 协议原因 NO_SUPPORT。 */ NO_SUPPORT,
    /** 协议原因 CONFLICTING_SOURCES。 */ CONFLICTING_SOURCES,
    /** 协议原因 VERSION_MISMATCH。 */ VERSION_MISMATCH,
    /** 协议原因 MISSING_CONTEXT。 */ MISSING_CONTEXT,
    /** 协议原因 NETWORK_UNCERTAIN。 */ NETWORK_UNCERTAIN,
    /** 协议原因 IDEMPOTENCY_CONFLICT。 */ IDEMPOTENCY_CONFLICT,
    /** 协议原因 STALE_REQUEST。 */ STALE_REQUEST,
    /** 协议原因 AUTH_CHANGED。 */ AUTH_CHANGED,
    /** 协议原因 ACCESS_REVOKED。 */ ACCESS_REVOKED,
    /** 协议原因 EVIDENCE_INVALIDATED。 */ EVIDENCE_INVALIDATED,
    /** 协议原因 SESSION_CLOSED。 */ SESSION_CLOSED,
    /** 协议原因 SESSION_EXPIRED。 */ SESSION_EXPIRED,
    /** 协议原因 DATABASE_BUSY。 */ DATABASE_BUSY,
    /** 协议原因 STORAGE_UNAVAILABLE。 */ STORAGE_UNAVAILABLE,
    /** 协议原因 COMMIT_UNCERTAIN。 */ COMMIT_UNCERTAIN,
    /** 协议原因 RESOURCE_LIMIT。 */ RESOURCE_LIMIT,
    /** 协议原因 INDEX_INVALID。 */ INDEX_INVALID,
    /** 协议原因 CLEANUP_PENDING。 */ CLEANUP_PENDING,
    /** 协议原因 MODEL_TEMPORARY。 */ MODEL_TEMPORARY,
    /** 协议原因 MODEL_CONFIGURATION。 */ MODEL_CONFIGURATION,
    /** 协议原因 BUDGET_EXHAUSTED。 */ BUDGET_EXHAUSTED,
    /** 协议原因 MODEL_PROTOCOL。 */ MODEL_PROTOCOL,
    /** 协议原因 UNSUPPORTED_ANSWER。 */ UNSUPPORTED_ANSWER,
    /** 协议原因 UNTRUSTED_INSTRUCTION。 */ UNTRUSTED_INSTRUCTION,
    /** 协议原因 ENDPOINT_REJECTED。 */ ENDPOINT_REJECTED,
    /** 协议原因 PROFILE_CHANGED。 */ PROFILE_CHANGED,
    /** 协议原因 GRAPH_INVALID。 */ GRAPH_INVALID,
    /** 协议原因 AMBIGUOUS_CONTACT。 */ AMBIGUOUS_CONTACT,
    /** 协议原因 GRAPH_LIMIT。 */ GRAPH_LIMIT,
    /** 协议原因 SOURCE_INVALID。 */ SOURCE_INVALID,
    /** 协议原因 DECRYPTION_FAILED。 */ DECRYPTION_FAILED,
    /** 协议原因 RESULT_STALE。 */ RESULT_STALE,
    /** 协议原因 INVALID_GRAPH_QUERY。 */ INVALID_GRAPH_QUERY,
    /** 协议原因 CONFIG_INVALID。 */ CONFIG_INVALID,
    /** 协议原因 RESTORE_VALIDATION。 */ RESTORE_VALIDATION,
    /** 协议原因 CLOCK_UNRELIABLE。 */ CLOCK_UNRELIABLE
}
